version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: neznamy-postgres
    environment:
      POSTGRES_DB: neznamy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c shared_preload_libraries=pg_trgm
    restart: unless-stopped

volumes:
  postgres_data:

